export const access_key = 'http://api-lulu.hibitbyte.com/product/allProducts?mykey=CgGV3Yu3/6w47TkWoHc2k2gl1GXFq5xFGERYFjSdzAIOf6xqA8gAFdjnWR7Hx/xdUmqNvEOdffny%2Bn9bGtt6vQ=='
export const SELECTED_IMAGE = 'selectedImage'


export const actionType={
    //all filter types
    SET_INITAL_FILTERS:'SET_INITAL_FILTERS',
    SET_GENDER_FILTER:'SET_GENDER_FILTER',
    SET_CATEGORY_FILTER:'SET_CATEGORY_FILTER',
    SET_TYPE_FILTER:'SET_TYPE_FILTER',
    SET_ACTIVITY_FILTER:'SET_ACTIVITY_FILTER',
    SET_SIZE_FILTER:'SET_SIZE_FILTER',
    SET_SIZETYPE_FILTER:'SET_SIZETYPE_FILTER',
    SET_COLOR_FILTER:'SET_COLOR_FILTER',
    SET_COLLECTION_FILTER:'SET_COLLECTION_FILTER',
    SET_FEATURES_FILTER:'SET_FEATURE_FILTER',
    SET_CLIMATE_FILTER:'SET_CLIMATE_FILTER',
    SET_FABRIC_FILTER:'SET_FABRIC_FILTER',
    //for fetch
    LOADING: 'LOADING',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_ERROR: 'FETCH_ERROR',
    FETCH_FILTER_DATA_SUCCESS:'FETCH_FILTER_DATA_SUCCESS',
    FETCH_FILTER_DATA_FAILURE:'FETCH_FILTER_DATA_FAILURE',
    SET_PRODUCT_ID:'SET_PRODUCT_ID',
    SET_COLOR_ID:'SET_COLOR_ID',
    SET_SELECTED_PICTURE:'SET_SELECTED_PICTURE'

}